class CallNextNotUsedError(Exception):
    pass


class NothingReturnedError(Exception):
    pass